language: python
python:
  - "3.6"
  - "3.8"
addons:
  ssh_known_hosts: $WASTELAND
install:
  - pip install -r requirements.txt
script:
  - export HOME_DIR=$HOME_DIR
  - export PORTFOLIO_DIR=$PORTFOLIO_DIR
  - pytest
  - python ./hello.py
before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
    -in travis_rsa.enc -out travis_rsa -d
env:
  global:
    - secure: BAUd9759fj8nXja8soctioga/VT+hSs92eVJNKQxcqUCHlk93sDa8BPraHFITrh8G+jDYPa3+FEz3HVoqqB86imXHG1esupfuu8LIpAWbJ6BE2TbBfp5cRo2kgi5x7yyalTe0aSiuf/g0+rQX3Z24fLtvdpagBDjVfHkqpTNh3H4lGux4Hyh4SqVrlRopcWNJp3vFLwDYxLk40/kKmlzMabUHfohgMNdQU3I/6fSKS9XMQkkvs0WN9QAdav33ovRopSTn6LEd6FTAetF/xbWT4UYQ1xcHSsfQw9VnWEKvRD29xLP7F26bf86+zS2pY7ViK6FsCOCR643wk/Mv9tp26w5nY4qCCkzjEZIgYwEjYpwp94vtuTPtfk235OuBzkZVJmdYgxRyUWwNCd7Rg5xAvGwaXqAFIf72yAQNJFHbrqFrt2TlSg3A7c1CWx5iWCDlenyLFBvfPb4B24KNpL+R+vMrhZDyjIjInpsMzzSqCZT9RwdoY28/vQs677nyawQuc+X75lGOII1Zqgv7UN1/PV9oGM2maGeVfBTDf4ztGJkBx/1Fhi4ItnpBfJ0hrI3BpNmNwmom5CebH/QdsJxlFqoHH7LB74oxuCyvZuvfLD44k+lNmTEjwMHZT6hThQ/brOvjwtgJoViKH3CKAr28kBuxRsv32t7oojl3mI+gSc=
    - secure: QwMw26huO9DuYEG6WbAtUwWZ5Cw5kx5yN9pD7TTV+FSmQ0vUkWrj4kfPP0PrT5aQMPPsHJD/mmkq3EAXGZ3LBbe0HIe2KT/8xhFTYd9a5ihwXwdEoGCW9bcxlDITvSdStpZiJh6gIxyfCfOlqKOtx5B+5XLUWFABuJM0e+x1QOtesrZ7gCtnPjh5FngK1OOm69IzBm3aC0LfDfUnhHnbrlukfOb280+jNdgxZrPmamfaoZsevmESfhrZaHr49FSHz5/I1YRCZP5Qy8wCqdlA3X/C98Ey0hP+5IahE4cTJIraZOWSci1VpQ9C16TZ2RdkjHK/6hNjhR7HH9QNS1WINWRXGzPBIIoCQ1m794+Q0+4kPxVdn8lF5cilfHfPqL01qmZcFnrLU1fXtciTLUubnNUfhZvy7Qg/rq2WAkZ26xrVkzzohxKcAbU1BF4FZ7LNZQQA+Az1vCtwYoeNkalgXLREyHAbVURfj1YWoMc/Lp6kZR8bM+ORrABX46eD/GF0VOfDuO6YXDq7yhQ4X+PXNFfW2JBR9CzenBEsyuRpShL+6XJRmlKpiYMN0GgEMNvEcKKN3P/vy1rcqHsbE/t9vW3NdQESES6I0psOUcSthCWJAQOIwCZZ4znoiD/2yQOQFtYv2TmDIrNjjrwWcJAQU9QJdHpBGgIV/kBbhySnLDM=
    - secure: WKkS64gfQjXeLLr6ZT/mDo53eSz4Uf7KDVs0SyAcAErwh02Im6AvVInF8AoJk9sN9PK5m266ehqQKAgTpvHaC5tg1ZlBzKi2MMNREtXPopsSWelWrgu5uKzjE4h8Px+XBvmO15eYhvVlnj8TME/o+osGEXER7YSu7m58Z+O1Mrj3uOVibnd1VAdyRdPWQ+LFGzF04N0jJ/h7BMLSI+aTjD8QbdzitRqj9ME3ZCSZ1zbX7gMxYBd5OT/QVD+aefPL/edjNtZUf6Sg5Cbi49e64hZzqAnepxcYRBpkd8v5UQ4QHa0kn8xxm4LNW8jRRSKlsR5YBsGSLk67OX4krTUmBAGvQkX9Ay/3/DXPUv8gnHGOvM+KU4QyeQuNZggmtESenTpaBlVa9RF3C7iyHRYF+Yhc0SbpyFZwdykghod08mcfdlYHZhR42HrnIAiTp3kRCictZzDr60mcFAvKlTrjD/gP+nJtR2kM9o34ifIDUeK4Emxq/gObSAH9Ec3+TZNJH9DAiPN6l1oyYwKY8083WGl8iRw8lvtV2AM+TRbSp7jPz2FTW+n42Sska5gaX+tO6o+Zhzatf/fEwSLzMd2CzkNYtiQ+npqQfEkJSyq9I16lULfUdvRM7LuC4pJ8hX6IjLsMl7tKBDJYPH5zDLZYiiKlJzP4ZVSVQ4TuBwUDgDA=
after_success:
  - bash ./deploy.sh
