language: python
python:
    - "3.3"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
env:
    - DEBUG = False
    - TESTING = False
    - CSRF_ENABLED = True
    - SECRET_KEY = 'This is secret'
script:
    - python -m unittest discover
