language: python
python:
- '3.6'
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
addons:
  ssh_known_hosts: "$WASTELAND"
install:
- pip install -r requirements.txt
script:
- pytest
- python ./hello.py
after_success:
- bash ./deploy.sh
env:
  global:
  - secure: JOutty1dW7+Mbh3ZQGcQqqk6yzsrobWNz8zTQPcsi2N29309b13zZjysuS0/NORYtjiajR4n2qgBE9AZhNwmZ1RuNsK4Izn8wF7fGpe9RgRVdk+f7bZJgBYGmgfwpxzOlTeQZQRbOkvbIE60duR798Qc3Kgf9qb6uKklpI74XvsIvDW3rcNmLqOxi6JfYICG8Ld8mJ4SL7lAEkMrrqAzNq1njzkLJpTlq41s3sYk89SonUaCrDjGANjR4WvCt5iZbS6r0UlrIqEBxCpezV9ynO9W952l1hmL1GOBHCBhsBD+FlyzeJaLsWn1tkd48NAdN5jwFLd2UpYZYne6O/6ATs0hJuzW/nO9lrhtHqT3pIIN7aUsMJLvOJnUIXfkrz/8nEQvGlSNk8hURZFvf3Az+KTDycz5WdhqJMIfQH8dmhtU7BvHOuV4cZZh98DK7hnzToIgqdmEp92iQ65KArY08aR4DHH8u+weZFgUgv0giIGZ8705EoyPA/18ey/wnXGf/mp7TVVKLkBng/SVnQt+4wg3hFOeiEf/rNff8yB5rvID6fQV7gDsiDKCTjA5zvPLh59dYH7xN7c/1z1v4CNFeWc4ogCgKLIPwcO4hMho9EwtiAivGuCpqzLoXl3nsCIy+CbaiN+0IiBggGsl6d+FoPsbmHugYu5rWr/Kaql/Fno=
  - secure: smMJnqZi3XBZA9UNu/T/n32DlI12Lxi8tyVeVFBQYascolgEXijXD1F4iTK/QMM2W/F7f1vqijb/MHIsNrrKsNxOj9ctKzcHRSJjqeUrOy8g/0G3q2+I230KHIS1ansM7DuHTVDC5L3/pNUPOOi7iVSsgwuvaZIkrKPF3cMNpKqxTOKtgwwvIKoQMlZL/mgvNevtDncQ3r9I2YR5L7cqeM7Gk7rzPeacTcGMFPrk42azOXGjhd7qWL9AW9UMr2jF3kXzSqmFUDxy3cPlEvggH6Su16pIFgAaG/J7Pqdam/HlLAS3nqAmMvL5nUtxVjNHsCtJkGkSULVb7rxJ1v6wCNqAgQ/vg3FjVrTICHHEcwUEpsCtkwU21XPGsAbSWNpRxX13ZT1B3WSzeJN1jJ3su5qAAz5EG1nBpHHO0uCU7lRNmnSnubuykKVmz7NITTA2ACB1HnjAmQNUxfkJDtLNZgpxDtr1/yXZV0052UsIYPOUUHv1IRWFzkDw+hV3gr/aEfj7IRbp0H2zPcKzb3Ze3ONxKXZVSBkBPzbmDO7rhACa6nFRV/VGDVS8YPxbFOcEE58cEvpTqp5iRFgOtx0TShlHOXCvkqfD/7AJ4j1c4nIHegj3FQbPx1Ai+pQy5uzYDw7Ai+hWpZuIgwGJvM0scZ062g37O+6ZQBipmdZaoFo=
  - secure: Q6g4/Zzlj4fnnm2rymkY1S36bTTuGQCs9CmxUCetxbZoKbPvGBICKi0qDIuCRFMU0s0jBxaVyeLS+8GPscKO46OuwB3/xsIt3F1CiMhuTlI2EZ8g/CVZHwOAtHtxn27yZCWFyhnfqmcLODdTVL9EiVc4Y/0ecMKyNnqSuDHThCoweoPqSqG6DeLkTsThIvtYVNAONoRGoYsAGtWR9gOFFskHquujS1ezqNTcEfueUekqR26YAplr4RA7aTPpm44nZv4txL4Jbh5mJ6uP9DfaIz3kg/PshUXpFPUGIGnDG7ajDUy7v2+niAidVoXFXZbj8MlF2pUOZf1uYjQrLfUd2mEEF2Z3YIA87tO4rXeAbyWxzKWDDjqnZAd+LfAPRteljFCKwBX7R0ABmZSPe5R0DVxj0AF9BxGGV2jef6UchIfFggH2jbaFvgd1EY6Y7i8MBuWd5zoi09FYmGX24wc0tLLZheVLbRTj2nxV/UOR87kR3yqY7SIz8yIVlvS0PQSyuB+31BziTDGULXC6D9dq38JfZoNsQ0YpYZRPzhCD5DMInopZokjObW4lEYCOnOvh5kfEXGvujyGnSEtwKSsd2dEPjCZMbKgYMAovFrwSS9cC+4CKdOkRdzqqI6/UlrX1mTcd3Uml9STEOFF1+D3p6/PgnAXnlRoDyTWhjqFD3KQ=
