# set base image (host OS)
FROM ubuntu:latest
# set the working directory in the container
WORKDIR /home/app
# Copy files
COPY . .
# Init env
RUN apt-get update && apt-get install -y make
RUN make init-env
# Init app deps
RUN make deps dtype=development
# Run app
CMD make -w run fenv=development